#!/bin/bash

set -e

# Check dependencies

if [ -z "$(command -v adb)" ]
then
  echo "$CMD_NAME: ADB not installed."
  exit 1
fi

# Check root

USER=$(echo '
su
whoami' | adb shell)

if [ "$USER" == "root" ]
then
  echo 'adb-check-root: ADB shell has root.';
  exit 0
fi

echo 'adb-check-root: ADB shell does not have root.'
exit 1
